//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Service.SiteService.SiteServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site_Cates", Namespace="http://schemas.datacontract.org/2004/07/Site.SiteModel")]
    [System.SerializableAttribute()]
    public partial class Site_Cates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime c_createTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_createUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_gidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool c_isMainCateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_pathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_tableIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime c_createTime {
            get {
                return this.c_createTimeField;
            }
            set {
                if ((this.c_createTimeField.Equals(value) != true)) {
                    this.c_createTimeField = value;
                    this.RaisePropertyChanged("c_createTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_createUser {
            get {
                return this.c_createUserField;
            }
            set {
                if ((object.ReferenceEquals(this.c_createUserField, value) != true)) {
                    this.c_createUserField = value;
                    this.RaisePropertyChanged("c_createUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_gid {
            get {
                return this.c_gidField;
            }
            set {
                if ((object.ReferenceEquals(this.c_gidField, value) != true)) {
                    this.c_gidField = value;
                    this.RaisePropertyChanged("c_gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_id {
            get {
                return this.c_idField;
            }
            set {
                if ((this.c_idField.Equals(value) != true)) {
                    this.c_idField = value;
                    this.RaisePropertyChanged("c_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool c_isMainCate {
            get {
                return this.c_isMainCateField;
            }
            set {
                if ((this.c_isMainCateField.Equals(value) != true)) {
                    this.c_isMainCateField = value;
                    this.RaisePropertyChanged("c_isMainCate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_name {
            get {
                return this.c_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.c_nameField, value) != true)) {
                    this.c_nameField = value;
                    this.RaisePropertyChanged("c_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_path {
            get {
                return this.c_pathField;
            }
            set {
                if ((object.ReferenceEquals(this.c_pathField, value) != true)) {
                    this.c_pathField = value;
                    this.RaisePropertyChanged("c_path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_tableId {
            get {
                return this.c_tableIdField;
            }
            set {
                if ((this.c_tableIdField.Equals(value) != true)) {
                    this.c_tableIdField = value;
                    this.RaisePropertyChanged("c_tableId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_type {
            get {
                return this.c_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.c_typeField, value) != true)) {
                    this.c_typeField = value;
                    this.RaisePropertyChanged("c_type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site_CMSPage", Namespace="http://schemas.datacontract.org/2004/07/Site.SiteModel")]
    [System.SerializableAttribute()]
    public partial class Site_CMSPage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime p_createTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_createUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_filePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_gidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int p_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_pageDutyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_pathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int p_siteNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_tempPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime p_createTime {
            get {
                return this.p_createTimeField;
            }
            set {
                if ((this.p_createTimeField.Equals(value) != true)) {
                    this.p_createTimeField = value;
                    this.RaisePropertyChanged("p_createTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_createUser {
            get {
                return this.p_createUserField;
            }
            set {
                if ((object.ReferenceEquals(this.p_createUserField, value) != true)) {
                    this.p_createUserField = value;
                    this.RaisePropertyChanged("p_createUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_filePath {
            get {
                return this.p_filePathField;
            }
            set {
                if ((object.ReferenceEquals(this.p_filePathField, value) != true)) {
                    this.p_filePathField = value;
                    this.RaisePropertyChanged("p_filePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_gid {
            get {
                return this.p_gidField;
            }
            set {
                if ((object.ReferenceEquals(this.p_gidField, value) != true)) {
                    this.p_gidField = value;
                    this.RaisePropertyChanged("p_gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int p_id {
            get {
                return this.p_idField;
            }
            set {
                if ((this.p_idField.Equals(value) != true)) {
                    this.p_idField = value;
                    this.RaisePropertyChanged("p_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_name {
            get {
                return this.p_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.p_nameField, value) != true)) {
                    this.p_nameField = value;
                    this.RaisePropertyChanged("p_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_pageDuty {
            get {
                return this.p_pageDutyField;
            }
            set {
                if ((object.ReferenceEquals(this.p_pageDutyField, value) != true)) {
                    this.p_pageDutyField = value;
                    this.RaisePropertyChanged("p_pageDuty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_path {
            get {
                return this.p_pathField;
            }
            set {
                if ((object.ReferenceEquals(this.p_pathField, value) != true)) {
                    this.p_pathField = value;
                    this.RaisePropertyChanged("p_path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int p_siteName {
            get {
                return this.p_siteNameField;
            }
            set {
                if ((this.p_siteNameField.Equals(value) != true)) {
                    this.p_siteNameField = value;
                    this.RaisePropertyChanged("p_siteName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_tempPath {
            get {
                return this.p_tempPathField;
            }
            set {
                if ((object.ReferenceEquals(this.p_tempPathField, value) != true)) {
                    this.p_tempPathField = value;
                    this.RaisePropertyChanged("p_tempPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site_CMSBlock", Namespace="http://schemas.datacontract.org/2004/07/Site.SiteModel")]
    [System.SerializableAttribute()]
    public partial class Site_CMSBlock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime b_createTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string b_createUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string b_gidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int b_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string b_img_sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string b_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string b_p_gidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string b_pathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime b_createTime {
            get {
                return this.b_createTimeField;
            }
            set {
                if ((this.b_createTimeField.Equals(value) != true)) {
                    this.b_createTimeField = value;
                    this.RaisePropertyChanged("b_createTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string b_createUser {
            get {
                return this.b_createUserField;
            }
            set {
                if ((object.ReferenceEquals(this.b_createUserField, value) != true)) {
                    this.b_createUserField = value;
                    this.RaisePropertyChanged("b_createUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string b_gid {
            get {
                return this.b_gidField;
            }
            set {
                if ((object.ReferenceEquals(this.b_gidField, value) != true)) {
                    this.b_gidField = value;
                    this.RaisePropertyChanged("b_gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int b_id {
            get {
                return this.b_idField;
            }
            set {
                if ((this.b_idField.Equals(value) != true)) {
                    this.b_idField = value;
                    this.RaisePropertyChanged("b_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string b_img_size {
            get {
                return this.b_img_sizeField;
            }
            set {
                if ((object.ReferenceEquals(this.b_img_sizeField, value) != true)) {
                    this.b_img_sizeField = value;
                    this.RaisePropertyChanged("b_img_size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string b_name {
            get {
                return this.b_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.b_nameField, value) != true)) {
                    this.b_nameField = value;
                    this.RaisePropertyChanged("b_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string b_p_gid {
            get {
                return this.b_p_gidField;
            }
            set {
                if ((object.ReferenceEquals(this.b_p_gidField, value) != true)) {
                    this.b_p_gidField = value;
                    this.RaisePropertyChanged("b_p_gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string b_path {
            get {
                return this.b_pathField;
            }
            set {
                if ((object.ReferenceEquals(this.b_pathField, value) != true)) {
                    this.b_pathField = value;
                    this.RaisePropertyChanged("b_path");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site_CMSItem", Namespace="http://schemas.datacontract.org/2004/07/Site.SiteModel")]
    [System.SerializableAttribute()]
    public partial class Site_CMSItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string i_b_gidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string i_c_gidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string i_c_img_srcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string i_c_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime i_createTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string i_createUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string i_gidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int i_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string i_introField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string i_p_gidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int i_sortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int i_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string i_subTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string i_titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string i_b_gid {
            get {
                return this.i_b_gidField;
            }
            set {
                if ((object.ReferenceEquals(this.i_b_gidField, value) != true)) {
                    this.i_b_gidField = value;
                    this.RaisePropertyChanged("i_b_gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string i_c_gid {
            get {
                return this.i_c_gidField;
            }
            set {
                if ((object.ReferenceEquals(this.i_c_gidField, value) != true)) {
                    this.i_c_gidField = value;
                    this.RaisePropertyChanged("i_c_gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string i_c_img_src {
            get {
                return this.i_c_img_srcField;
            }
            set {
                if ((object.ReferenceEquals(this.i_c_img_srcField, value) != true)) {
                    this.i_c_img_srcField = value;
                    this.RaisePropertyChanged("i_c_img_src");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string i_c_type {
            get {
                return this.i_c_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.i_c_typeField, value) != true)) {
                    this.i_c_typeField = value;
                    this.RaisePropertyChanged("i_c_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime i_createTime {
            get {
                return this.i_createTimeField;
            }
            set {
                if ((this.i_createTimeField.Equals(value) != true)) {
                    this.i_createTimeField = value;
                    this.RaisePropertyChanged("i_createTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string i_createUser {
            get {
                return this.i_createUserField;
            }
            set {
                if ((object.ReferenceEquals(this.i_createUserField, value) != true)) {
                    this.i_createUserField = value;
                    this.RaisePropertyChanged("i_createUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string i_gid {
            get {
                return this.i_gidField;
            }
            set {
                if ((object.ReferenceEquals(this.i_gidField, value) != true)) {
                    this.i_gidField = value;
                    this.RaisePropertyChanged("i_gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int i_id {
            get {
                return this.i_idField;
            }
            set {
                if ((this.i_idField.Equals(value) != true)) {
                    this.i_idField = value;
                    this.RaisePropertyChanged("i_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string i_intro {
            get {
                return this.i_introField;
            }
            set {
                if ((object.ReferenceEquals(this.i_introField, value) != true)) {
                    this.i_introField = value;
                    this.RaisePropertyChanged("i_intro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string i_p_gid {
            get {
                return this.i_p_gidField;
            }
            set {
                if ((object.ReferenceEquals(this.i_p_gidField, value) != true)) {
                    this.i_p_gidField = value;
                    this.RaisePropertyChanged("i_p_gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int i_sort {
            get {
                return this.i_sortField;
            }
            set {
                if ((this.i_sortField.Equals(value) != true)) {
                    this.i_sortField = value;
                    this.RaisePropertyChanged("i_sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int i_status {
            get {
                return this.i_statusField;
            }
            set {
                if ((this.i_statusField.Equals(value) != true)) {
                    this.i_statusField = value;
                    this.RaisePropertyChanged("i_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string i_subTitle {
            get {
                return this.i_subTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.i_subTitleField, value) != true)) {
                    this.i_subTitleField = value;
                    this.RaisePropertyChanged("i_subTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string i_title {
            get {
                return this.i_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.i_titleField, value) != true)) {
                    this.i_titleField = value;
                    this.RaisePropertyChanged("i_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site_Content", Namespace="http://schemas.datacontract.org/2004/07/Site.SiteModel")]
    [System.SerializableAttribute()]
    public partial class Site_Content : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_c_gidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_contentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime c_createTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_createUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_createUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_createUserNickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_gidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_img_srcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_introField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_keywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool c_stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_sub_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime c_updateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_c_gid {
            get {
                return this.c_c_gidField;
            }
            set {
                if ((object.ReferenceEquals(this.c_c_gidField, value) != true)) {
                    this.c_c_gidField = value;
                    this.RaisePropertyChanged("c_c_gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_content {
            get {
                return this.c_contentField;
            }
            set {
                if ((object.ReferenceEquals(this.c_contentField, value) != true)) {
                    this.c_contentField = value;
                    this.RaisePropertyChanged("c_content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime c_createTime {
            get {
                return this.c_createTimeField;
            }
            set {
                if ((this.c_createTimeField.Equals(value) != true)) {
                    this.c_createTimeField = value;
                    this.RaisePropertyChanged("c_createTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_createUserId {
            get {
                return this.c_createUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.c_createUserIdField, value) != true)) {
                    this.c_createUserIdField = value;
                    this.RaisePropertyChanged("c_createUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_createUserName {
            get {
                return this.c_createUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.c_createUserNameField, value) != true)) {
                    this.c_createUserNameField = value;
                    this.RaisePropertyChanged("c_createUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_createUserNickName {
            get {
                return this.c_createUserNickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.c_createUserNickNameField, value) != true)) {
                    this.c_createUserNickNameField = value;
                    this.RaisePropertyChanged("c_createUserNickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_gid {
            get {
                return this.c_gidField;
            }
            set {
                if ((object.ReferenceEquals(this.c_gidField, value) != true)) {
                    this.c_gidField = value;
                    this.RaisePropertyChanged("c_gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_id {
            get {
                return this.c_idField;
            }
            set {
                if ((this.c_idField.Equals(value) != true)) {
                    this.c_idField = value;
                    this.RaisePropertyChanged("c_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_img_src {
            get {
                return this.c_img_srcField;
            }
            set {
                if ((object.ReferenceEquals(this.c_img_srcField, value) != true)) {
                    this.c_img_srcField = value;
                    this.RaisePropertyChanged("c_img_src");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_intro {
            get {
                return this.c_introField;
            }
            set {
                if ((object.ReferenceEquals(this.c_introField, value) != true)) {
                    this.c_introField = value;
                    this.RaisePropertyChanged("c_intro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_keywords {
            get {
                return this.c_keywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.c_keywordsField, value) != true)) {
                    this.c_keywordsField = value;
                    this.RaisePropertyChanged("c_keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool c_state {
            get {
                return this.c_stateField;
            }
            set {
                if ((this.c_stateField.Equals(value) != true)) {
                    this.c_stateField = value;
                    this.RaisePropertyChanged("c_state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_status {
            get {
                return this.c_statusField;
            }
            set {
                if ((this.c_statusField.Equals(value) != true)) {
                    this.c_statusField = value;
                    this.RaisePropertyChanged("c_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_sub_title {
            get {
                return this.c_sub_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.c_sub_titleField, value) != true)) {
                    this.c_sub_titleField = value;
                    this.RaisePropertyChanged("c_sub_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_title {
            get {
                return this.c_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.c_titleField, value) != true)) {
                    this.c_titleField = value;
                    this.RaisePropertyChanged("c_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime c_updateTime {
            get {
                return this.c_updateTimeField;
            }
            set {
                if ((this.c_updateTimeField.Equals(value) != true)) {
                    this.c_updateTimeField = value;
                    this.RaisePropertyChanged("c_updateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.jsonyang.com", ConfigurationName="SiteServices.ISiteService")]
    public interface ISiteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_Insert", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_InsertResponse")]
        int Site_Cates_Insert(Site.Service.SiteService.SiteServices.Site_Cates obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_Insert", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_InsertResponse")]
        System.Threading.Tasks.Task<int> Site_Cates_InsertAsync(Site.Service.SiteService.SiteServices.Site_Cates obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_DeleteByc_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_DeleteByc_gidResponse")]
        int Site_Cates_DeleteByc_gid(string c_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_DeleteByc_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_DeleteByc_gidResponse")]
        System.Threading.Tasks.Task<int> Site_Cates_DeleteByc_gidAsync(string c_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_UpdateByc_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_UpdateByc_gidResponse")]
        int Site_Cates_UpdateByc_gid(Site.Service.SiteService.SiteServices.Site_Cates obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_UpdateByc_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_UpdateByc_gidResponse")]
        System.Threading.Tasks.Task<int> Site_Cates_UpdateByc_gidAsync(Site.Service.SiteService.SiteServices.Site_Cates obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_SelectByc_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_SelectByc_gidResponse")]
        Site.Service.SiteService.SiteServices.Site_Cates Site_Cates_SelectByc_gid(string c_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_SelectByc_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_SelectByc_gidResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Cates> Site_Cates_SelectByc_gidAsync(string c_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_SelectBaseCateByc_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_SelectBaseCateByc_gidResponse" +
            "")]
        Site.Service.SiteService.SiteServices.Site_Cates Site_Cates_SelectBaseCateByc_gid(string c_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_SelectBaseCateByc_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_SelectBaseCateByc_gidResponse" +
            "")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Cates> Site_Cates_SelectBaseCateByc_gidAsync(string c_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_SelectByc_id", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_SelectByc_idResponse")]
        Site.Service.SiteService.SiteServices.Site_Cates Site_Cates_SelectByc_id(int c_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_SelectByc_id", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_SelectByc_idResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Cates> Site_Cates_SelectByc_idAsync(int c_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_SelectPage", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_SelectPageResponse")]
        Site.Service.SiteService.SiteServices.Site_Cates_SelectPageResponse Site_Cates_SelectPage(Site.Service.SiteService.SiteServices.Site_Cates_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Cates_SelectPage", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Cates_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Cates_SelectPageResponse> Site_Cates_SelectPageAsync(Site.Service.SiteService.SiteServices.Site_Cates_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSPage_Insert", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSPage_InsertResponse")]
        int Site_CMSPage_Insert(Site.Service.SiteService.SiteServices.Site_CMSPage obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSPage_Insert", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSPage_InsertResponse")]
        System.Threading.Tasks.Task<int> Site_CMSPage_InsertAsync(Site.Service.SiteService.SiteServices.Site_CMSPage obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSPage_DeleteByp_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSPage_DeleteByp_gidResponse")]
        int Site_CMSPage_DeleteByp_gid(string p_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSPage_DeleteByp_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSPage_DeleteByp_gidResponse")]
        System.Threading.Tasks.Task<int> Site_CMSPage_DeleteByp_gidAsync(string p_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSPage_UpdateByp_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSPage_UpdateByp_gidResponse")]
        int Site_CMSPage_UpdateByp_gid(Site.Service.SiteService.SiteServices.Site_CMSPage obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSPage_UpdateByp_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSPage_UpdateByp_gidResponse")]
        System.Threading.Tasks.Task<int> Site_CMSPage_UpdateByp_gidAsync(Site.Service.SiteService.SiteServices.Site_CMSPage obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSPage_SelectPage", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSPage_SelectPageResponse")]
        Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageResponse Site_CMSPage_SelectPage(Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSPage_SelectPage", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSPage_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageResponse> Site_CMSPage_SelectPageAsync(Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSPage_SelectByp_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSPage_SelectByp_gidResponse")]
        Site.Service.SiteService.SiteServices.Site_CMSPage Site_CMSPage_SelectByp_gid(string p_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSPage_SelectByp_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSPage_SelectByp_gidResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSPage> Site_CMSPage_SelectByp_gidAsync(string p_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSBlock_Insert", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSBlock_InsertResponse")]
        int Site_CMSBlock_Insert(Site.Service.SiteService.SiteServices.Site_CMSBlock obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSBlock_Insert", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSBlock_InsertResponse")]
        System.Threading.Tasks.Task<int> Site_CMSBlock_InsertAsync(Site.Service.SiteService.SiteServices.Site_CMSBlock obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSBlock_DeleteByb_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSBlock_DeleteByb_gidResponse")]
        int Site_CMSBlock_DeleteByb_gid(string b_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSBlock_DeleteByb_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSBlock_DeleteByb_gidResponse")]
        System.Threading.Tasks.Task<int> Site_CMSBlock_DeleteByb_gidAsync(string b_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSBlock_UpdateByb_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSBlock_UpdateByb_gidResponse")]
        int Site_CMSBlock_UpdateByb_gid(Site.Service.SiteService.SiteServices.Site_CMSBlock obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSBlock_UpdateByb_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSBlock_UpdateByb_gidResponse")]
        System.Threading.Tasks.Task<int> Site_CMSBlock_UpdateByb_gidAsync(Site.Service.SiteService.SiteServices.Site_CMSBlock obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSBlock_SelectByb_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSBlock_SelectByb_gidResponse")]
        Site.Service.SiteService.SiteServices.Site_CMSBlock Site_CMSBlock_SelectByb_gid(string b_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSBlock_SelectByb_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSBlock_SelectByb_gidResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSBlock> Site_CMSBlock_SelectByb_gidAsync(string b_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSBlock_SelectPage", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSBlock_SelectPageResponse")]
        Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageResponse Site_CMSBlock_SelectPage(Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSBlock_SelectPage", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSBlock_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageResponse> Site_CMSBlock_SelectPageAsync(Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_Insert", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_InsertResponse")]
        int Site_CMSItem_Insert(Site.Service.SiteService.SiteServices.Site_CMSItem obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_Insert", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_InsertResponse")]
        System.Threading.Tasks.Task<int> Site_CMSItem_InsertAsync(Site.Service.SiteService.SiteServices.Site_CMSItem obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_DeleteByi_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_DeleteByi_gidResponse")]
        int Site_CMSItem_DeleteByi_gid(string i_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_DeleteByi_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_DeleteByi_gidResponse")]
        System.Threading.Tasks.Task<int> Site_CMSItem_DeleteByi_gidAsync(string i_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_UpdateByi_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_UpdateByi_gidResponse")]
        int Site_CMSItem_UpdateByi_gid(Site.Service.SiteService.SiteServices.Site_CMSItem obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_UpdateByi_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_UpdateByi_gidResponse")]
        System.Threading.Tasks.Task<int> Site_CMSItem_UpdateByi_gidAsync(Site.Service.SiteService.SiteServices.Site_CMSItem obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectByi_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectByi_gidResponse")]
        Site.Service.SiteService.SiteServices.Site_CMSItem Site_CMSItem_SelectByi_gid(string i_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectByi_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectByi_gidResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSItem> Site_CMSItem_SelectByi_gidAsync(string i_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectByc_gidAndb_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectByc_gidAndb_gidRespon" +
            "se")]
        Site.Service.SiteService.SiteServices.Site_CMSItem Site_CMSItem_SelectByc_gidAndb_gid(string c_gid, string b_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectByc_gidAndb_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectByc_gidAndb_gidRespon" +
            "se")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSItem> Site_CMSItem_SelectByc_gidAndb_gidAsync(string c_gid, string b_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectPage", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectPageResponse")]
        Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageResponse Site_CMSItem_SelectPage(Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectPage", ReplyAction="http://service.jsonyang.com/ISiteService/Site_CMSItem_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageResponse> Site_CMSItem_SelectPageAsync(Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_Insert", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_InsertResponse")]
        int Site_Content_Insert(Site.Service.SiteService.SiteServices.Site_Content obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_Insert", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_InsertResponse")]
        System.Threading.Tasks.Task<int> Site_Content_InsertAsync(Site.Service.SiteService.SiteServices.Site_Content obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_DeleteByc_id", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_DeleteByc_idResponse")]
        int Site_Content_DeleteByc_id(string c_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_DeleteByc_id", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_DeleteByc_idResponse")]
        System.Threading.Tasks.Task<int> Site_Content_DeleteByc_idAsync(string c_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_UpdateByc_id", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_UpdateByc_idResponse")]
        int Site_Content_UpdateByc_id(Site.Service.SiteService.SiteServices.Site_Content obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_UpdateByc_id", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_UpdateByc_idResponse")]
        System.Threading.Tasks.Task<int> Site_Content_UpdateByc_idAsync(Site.Service.SiteService.SiteServices.Site_Content obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_SelectByc_id", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_SelectByc_idResponse")]
        Site.Service.SiteService.SiteServices.Site_Content Site_Content_SelectByc_id(string c_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_SelectByc_id", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_SelectByc_idResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Content> Site_Content_SelectByc_idAsync(string c_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_SelectByc_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_SelectByc_gidResponse")]
        Site.Service.SiteService.SiteServices.Site_Content Site_Content_SelectByc_gid(string c_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_SelectByc_gid", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_SelectByc_gidResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Content> Site_Content_SelectByc_gidAsync(string c_gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_SelectPage", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_SelectPageResponse")]
        Site.Service.SiteService.SiteServices.Site_Content_SelectPageResponse Site_Content_SelectPage(Site.Service.SiteService.SiteServices.Site_Content_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_SelectPage", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Content_SelectPageResponse> Site_Content_SelectPageAsync(Site.Service.SiteService.SiteServices.Site_Content_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_SelectPageByc_id", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_SelectPageByc_idResponse")]
        Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idResponse Site_Content_SelectPageByc_id(Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/ISiteService/Site_Content_SelectPageByc_id", ReplyAction="http://service.jsonyang.com/ISiteService/Site_Content_SelectPageByc_idResponse")]
        System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idResponse> Site_Content_SelectPageByc_idAsync(Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_Cates_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_Cates_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public string where;
        
        public Site_Cates_SelectPageRequest() {
        }
        
        public Site_Cates_SelectPageRequest(string cloumns, int pageIndex, int pageSize, string orderBy, string where) {
            this.cloumns = cloumns;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderBy = orderBy;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_Cates_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_Cates_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_Cates> Site_Cates_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public Site_Cates_SelectPageResponse() {
        }
        
        public Site_Cates_SelectPageResponse(System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_Cates> Site_Cates_SelectPageResult, int rowCount) {
            this.Site_Cates_SelectPageResult = Site_Cates_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_CMSPage_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_CMSPage_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public string where;
        
        public Site_CMSPage_SelectPageRequest() {
        }
        
        public Site_CMSPage_SelectPageRequest(string cloumns, int pageIndex, int pageSize, string orderBy, string where) {
            this.cloumns = cloumns;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderBy = orderBy;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_CMSPage_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_CMSPage_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_CMSPage> Site_CMSPage_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public Site_CMSPage_SelectPageResponse() {
        }
        
        public Site_CMSPage_SelectPageResponse(System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_CMSPage> Site_CMSPage_SelectPageResult, int rowCount) {
            this.Site_CMSPage_SelectPageResult = Site_CMSPage_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_CMSBlock_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_CMSBlock_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public string where;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public int pageSize;
        
        public Site_CMSBlock_SelectPageRequest() {
        }
        
        public Site_CMSBlock_SelectPageRequest(string cloumns, string orderBy, string where, int pageIndex, int pageSize) {
            this.cloumns = cloumns;
            this.orderBy = orderBy;
            this.where = where;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_CMSBlock_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_CMSBlock_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_CMSBlock> Site_CMSBlock_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public Site_CMSBlock_SelectPageResponse() {
        }
        
        public Site_CMSBlock_SelectPageResponse(System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_CMSBlock> Site_CMSBlock_SelectPageResult, int rowCount) {
            this.Site_CMSBlock_SelectPageResult = Site_CMSBlock_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_CMSItem_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_CMSItem_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public string where;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public int pageSize;
        
        public Site_CMSItem_SelectPageRequest() {
        }
        
        public Site_CMSItem_SelectPageRequest(string cloumns, string orderBy, string where, int pageIndex, int pageSize) {
            this.cloumns = cloumns;
            this.orderBy = orderBy;
            this.where = where;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_CMSItem_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_CMSItem_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_CMSItem> Site_CMSItem_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public Site_CMSItem_SelectPageResponse() {
        }
        
        public Site_CMSItem_SelectPageResponse(System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_CMSItem> Site_CMSItem_SelectPageResult, int rowCount) {
            this.Site_CMSItem_SelectPageResult = Site_CMSItem_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_Content_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_Content_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public string where;
        
        public Site_Content_SelectPageRequest() {
        }
        
        public Site_Content_SelectPageRequest(string cloumns, int pageIndex, int pageSize, string orderBy, string where) {
            this.cloumns = cloumns;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderBy = orderBy;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_Content_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_Content_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_Content> Site_Content_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public Site_Content_SelectPageResponse() {
        }
        
        public Site_Content_SelectPageResponse(System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_Content> Site_Content_SelectPageResult, int rowCount) {
            this.Site_Content_SelectPageResult = Site_Content_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_Content_SelectPageByc_id", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_Content_SelectPageByc_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public int cateId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        public Site_Content_SelectPageByc_idRequest() {
        }
        
        public Site_Content_SelectPageByc_idRequest(int cateId, int pageIndex, int pageSize) {
            this.cateId = cateId;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Site_Content_SelectPageByc_idResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Site_Content_SelectPageByc_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_Content> Site_Content_SelectPageByc_idResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public Site_Content_SelectPageByc_idResponse() {
        }
        
        public Site_Content_SelectPageByc_idResponse(System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_Content> Site_Content_SelectPageByc_idResult, int rowCount) {
            this.Site_Content_SelectPageByc_idResult = Site_Content_SelectPageByc_idResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISiteServiceChannel : Site.Service.SiteService.SiteServices.ISiteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteServiceClient : System.ServiceModel.ClientBase<Site.Service.SiteService.SiteServices.ISiteService>, Site.Service.SiteService.SiteServices.ISiteService {
        
        public SiteServiceClient() {
        }
        
        public SiteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Site_Cates_Insert(Site.Service.SiteService.SiteServices.Site_Cates obj) {
            return base.Channel.Site_Cates_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> Site_Cates_InsertAsync(Site.Service.SiteService.SiteServices.Site_Cates obj) {
            return base.Channel.Site_Cates_InsertAsync(obj);
        }
        
        public int Site_Cates_DeleteByc_gid(string c_gid) {
            return base.Channel.Site_Cates_DeleteByc_gid(c_gid);
        }
        
        public System.Threading.Tasks.Task<int> Site_Cates_DeleteByc_gidAsync(string c_gid) {
            return base.Channel.Site_Cates_DeleteByc_gidAsync(c_gid);
        }
        
        public int Site_Cates_UpdateByc_gid(Site.Service.SiteService.SiteServices.Site_Cates obj) {
            return base.Channel.Site_Cates_UpdateByc_gid(obj);
        }
        
        public System.Threading.Tasks.Task<int> Site_Cates_UpdateByc_gidAsync(Site.Service.SiteService.SiteServices.Site_Cates obj) {
            return base.Channel.Site_Cates_UpdateByc_gidAsync(obj);
        }
        
        public Site.Service.SiteService.SiteServices.Site_Cates Site_Cates_SelectByc_gid(string c_gid) {
            return base.Channel.Site_Cates_SelectByc_gid(c_gid);
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Cates> Site_Cates_SelectByc_gidAsync(string c_gid) {
            return base.Channel.Site_Cates_SelectByc_gidAsync(c_gid);
        }
        
        public Site.Service.SiteService.SiteServices.Site_Cates Site_Cates_SelectBaseCateByc_gid(string c_gid) {
            return base.Channel.Site_Cates_SelectBaseCateByc_gid(c_gid);
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Cates> Site_Cates_SelectBaseCateByc_gidAsync(string c_gid) {
            return base.Channel.Site_Cates_SelectBaseCateByc_gidAsync(c_gid);
        }
        
        public Site.Service.SiteService.SiteServices.Site_Cates Site_Cates_SelectByc_id(int c_id) {
            return base.Channel.Site_Cates_SelectByc_id(c_id);
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Cates> Site_Cates_SelectByc_idAsync(int c_id) {
            return base.Channel.Site_Cates_SelectByc_idAsync(c_id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.SiteService.SiteServices.Site_Cates_SelectPageResponse Site.Service.SiteService.SiteServices.ISiteService.Site_Cates_SelectPage(Site.Service.SiteService.SiteServices.Site_Cates_SelectPageRequest request) {
            return base.Channel.Site_Cates_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_Cates> Site_Cates_SelectPage(string cloumns, int pageIndex, int pageSize, string orderBy, string where, out int rowCount) {
            Site.Service.SiteService.SiteServices.Site_Cates_SelectPageRequest inValue = new Site.Service.SiteService.SiteServices.Site_Cates_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderBy = orderBy;
            inValue.where = where;
            Site.Service.SiteService.SiteServices.Site_Cates_SelectPageResponse retVal = ((Site.Service.SiteService.SiteServices.ISiteService)(this)).Site_Cates_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.Site_Cates_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Cates_SelectPageResponse> Site_Cates_SelectPageAsync(Site.Service.SiteService.SiteServices.Site_Cates_SelectPageRequest request) {
            return base.Channel.Site_Cates_SelectPageAsync(request);
        }
        
        public int Site_CMSPage_Insert(Site.Service.SiteService.SiteServices.Site_CMSPage obj) {
            return base.Channel.Site_CMSPage_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> Site_CMSPage_InsertAsync(Site.Service.SiteService.SiteServices.Site_CMSPage obj) {
            return base.Channel.Site_CMSPage_InsertAsync(obj);
        }
        
        public int Site_CMSPage_DeleteByp_gid(string p_gid) {
            return base.Channel.Site_CMSPage_DeleteByp_gid(p_gid);
        }
        
        public System.Threading.Tasks.Task<int> Site_CMSPage_DeleteByp_gidAsync(string p_gid) {
            return base.Channel.Site_CMSPage_DeleteByp_gidAsync(p_gid);
        }
        
        public int Site_CMSPage_UpdateByp_gid(Site.Service.SiteService.SiteServices.Site_CMSPage obj) {
            return base.Channel.Site_CMSPage_UpdateByp_gid(obj);
        }
        
        public System.Threading.Tasks.Task<int> Site_CMSPage_UpdateByp_gidAsync(Site.Service.SiteService.SiteServices.Site_CMSPage obj) {
            return base.Channel.Site_CMSPage_UpdateByp_gidAsync(obj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageResponse Site.Service.SiteService.SiteServices.ISiteService.Site_CMSPage_SelectPage(Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageRequest request) {
            return base.Channel.Site_CMSPage_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_CMSPage> Site_CMSPage_SelectPage(string cloumns, int pageIndex, int pageSize, string orderBy, string where, out int rowCount) {
            Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageRequest inValue = new Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderBy = orderBy;
            inValue.where = where;
            Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageResponse retVal = ((Site.Service.SiteService.SiteServices.ISiteService)(this)).Site_CMSPage_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.Site_CMSPage_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageResponse> Site_CMSPage_SelectPageAsync(Site.Service.SiteService.SiteServices.Site_CMSPage_SelectPageRequest request) {
            return base.Channel.Site_CMSPage_SelectPageAsync(request);
        }
        
        public Site.Service.SiteService.SiteServices.Site_CMSPage Site_CMSPage_SelectByp_gid(string p_gid) {
            return base.Channel.Site_CMSPage_SelectByp_gid(p_gid);
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSPage> Site_CMSPage_SelectByp_gidAsync(string p_gid) {
            return base.Channel.Site_CMSPage_SelectByp_gidAsync(p_gid);
        }
        
        public int Site_CMSBlock_Insert(Site.Service.SiteService.SiteServices.Site_CMSBlock obj) {
            return base.Channel.Site_CMSBlock_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> Site_CMSBlock_InsertAsync(Site.Service.SiteService.SiteServices.Site_CMSBlock obj) {
            return base.Channel.Site_CMSBlock_InsertAsync(obj);
        }
        
        public int Site_CMSBlock_DeleteByb_gid(string b_gid) {
            return base.Channel.Site_CMSBlock_DeleteByb_gid(b_gid);
        }
        
        public System.Threading.Tasks.Task<int> Site_CMSBlock_DeleteByb_gidAsync(string b_gid) {
            return base.Channel.Site_CMSBlock_DeleteByb_gidAsync(b_gid);
        }
        
        public int Site_CMSBlock_UpdateByb_gid(Site.Service.SiteService.SiteServices.Site_CMSBlock obj) {
            return base.Channel.Site_CMSBlock_UpdateByb_gid(obj);
        }
        
        public System.Threading.Tasks.Task<int> Site_CMSBlock_UpdateByb_gidAsync(Site.Service.SiteService.SiteServices.Site_CMSBlock obj) {
            return base.Channel.Site_CMSBlock_UpdateByb_gidAsync(obj);
        }
        
        public Site.Service.SiteService.SiteServices.Site_CMSBlock Site_CMSBlock_SelectByb_gid(string b_gid) {
            return base.Channel.Site_CMSBlock_SelectByb_gid(b_gid);
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSBlock> Site_CMSBlock_SelectByb_gidAsync(string b_gid) {
            return base.Channel.Site_CMSBlock_SelectByb_gidAsync(b_gid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageResponse Site.Service.SiteService.SiteServices.ISiteService.Site_CMSBlock_SelectPage(Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageRequest request) {
            return base.Channel.Site_CMSBlock_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_CMSBlock> Site_CMSBlock_SelectPage(string cloumns, string orderBy, string where, int pageIndex, int pageSize, out int rowCount) {
            Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageRequest inValue = new Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.orderBy = orderBy;
            inValue.where = where;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageResponse retVal = ((Site.Service.SiteService.SiteServices.ISiteService)(this)).Site_CMSBlock_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.Site_CMSBlock_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageResponse> Site_CMSBlock_SelectPageAsync(Site.Service.SiteService.SiteServices.Site_CMSBlock_SelectPageRequest request) {
            return base.Channel.Site_CMSBlock_SelectPageAsync(request);
        }
        
        public int Site_CMSItem_Insert(Site.Service.SiteService.SiteServices.Site_CMSItem obj) {
            return base.Channel.Site_CMSItem_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> Site_CMSItem_InsertAsync(Site.Service.SiteService.SiteServices.Site_CMSItem obj) {
            return base.Channel.Site_CMSItem_InsertAsync(obj);
        }
        
        public int Site_CMSItem_DeleteByi_gid(string i_gid) {
            return base.Channel.Site_CMSItem_DeleteByi_gid(i_gid);
        }
        
        public System.Threading.Tasks.Task<int> Site_CMSItem_DeleteByi_gidAsync(string i_gid) {
            return base.Channel.Site_CMSItem_DeleteByi_gidAsync(i_gid);
        }
        
        public int Site_CMSItem_UpdateByi_gid(Site.Service.SiteService.SiteServices.Site_CMSItem obj) {
            return base.Channel.Site_CMSItem_UpdateByi_gid(obj);
        }
        
        public System.Threading.Tasks.Task<int> Site_CMSItem_UpdateByi_gidAsync(Site.Service.SiteService.SiteServices.Site_CMSItem obj) {
            return base.Channel.Site_CMSItem_UpdateByi_gidAsync(obj);
        }
        
        public Site.Service.SiteService.SiteServices.Site_CMSItem Site_CMSItem_SelectByi_gid(string i_gid) {
            return base.Channel.Site_CMSItem_SelectByi_gid(i_gid);
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSItem> Site_CMSItem_SelectByi_gidAsync(string i_gid) {
            return base.Channel.Site_CMSItem_SelectByi_gidAsync(i_gid);
        }
        
        public Site.Service.SiteService.SiteServices.Site_CMSItem Site_CMSItem_SelectByc_gidAndb_gid(string c_gid, string b_gid) {
            return base.Channel.Site_CMSItem_SelectByc_gidAndb_gid(c_gid, b_gid);
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSItem> Site_CMSItem_SelectByc_gidAndb_gidAsync(string c_gid, string b_gid) {
            return base.Channel.Site_CMSItem_SelectByc_gidAndb_gidAsync(c_gid, b_gid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageResponse Site.Service.SiteService.SiteServices.ISiteService.Site_CMSItem_SelectPage(Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageRequest request) {
            return base.Channel.Site_CMSItem_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_CMSItem> Site_CMSItem_SelectPage(string cloumns, string orderBy, string where, int pageIndex, int pageSize, out int rowCount) {
            Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageRequest inValue = new Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.orderBy = orderBy;
            inValue.where = where;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageResponse retVal = ((Site.Service.SiteService.SiteServices.ISiteService)(this)).Site_CMSItem_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.Site_CMSItem_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageResponse> Site_CMSItem_SelectPageAsync(Site.Service.SiteService.SiteServices.Site_CMSItem_SelectPageRequest request) {
            return base.Channel.Site_CMSItem_SelectPageAsync(request);
        }
        
        public int Site_Content_Insert(Site.Service.SiteService.SiteServices.Site_Content obj) {
            return base.Channel.Site_Content_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> Site_Content_InsertAsync(Site.Service.SiteService.SiteServices.Site_Content obj) {
            return base.Channel.Site_Content_InsertAsync(obj);
        }
        
        public int Site_Content_DeleteByc_id(string c_id) {
            return base.Channel.Site_Content_DeleteByc_id(c_id);
        }
        
        public System.Threading.Tasks.Task<int> Site_Content_DeleteByc_idAsync(string c_id) {
            return base.Channel.Site_Content_DeleteByc_idAsync(c_id);
        }
        
        public int Site_Content_UpdateByc_id(Site.Service.SiteService.SiteServices.Site_Content obj) {
            return base.Channel.Site_Content_UpdateByc_id(obj);
        }
        
        public System.Threading.Tasks.Task<int> Site_Content_UpdateByc_idAsync(Site.Service.SiteService.SiteServices.Site_Content obj) {
            return base.Channel.Site_Content_UpdateByc_idAsync(obj);
        }
        
        public Site.Service.SiteService.SiteServices.Site_Content Site_Content_SelectByc_id(string c_id) {
            return base.Channel.Site_Content_SelectByc_id(c_id);
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Content> Site_Content_SelectByc_idAsync(string c_id) {
            return base.Channel.Site_Content_SelectByc_idAsync(c_id);
        }
        
        public Site.Service.SiteService.SiteServices.Site_Content Site_Content_SelectByc_gid(string c_gid) {
            return base.Channel.Site_Content_SelectByc_gid(c_gid);
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Content> Site_Content_SelectByc_gidAsync(string c_gid) {
            return base.Channel.Site_Content_SelectByc_gidAsync(c_gid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.SiteService.SiteServices.Site_Content_SelectPageResponse Site.Service.SiteService.SiteServices.ISiteService.Site_Content_SelectPage(Site.Service.SiteService.SiteServices.Site_Content_SelectPageRequest request) {
            return base.Channel.Site_Content_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_Content> Site_Content_SelectPage(string cloumns, int pageIndex, int pageSize, string orderBy, string where, out int rowCount) {
            Site.Service.SiteService.SiteServices.Site_Content_SelectPageRequest inValue = new Site.Service.SiteService.SiteServices.Site_Content_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderBy = orderBy;
            inValue.where = where;
            Site.Service.SiteService.SiteServices.Site_Content_SelectPageResponse retVal = ((Site.Service.SiteService.SiteServices.ISiteService)(this)).Site_Content_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.Site_Content_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Content_SelectPageResponse> Site_Content_SelectPageAsync(Site.Service.SiteService.SiteServices.Site_Content_SelectPageRequest request) {
            return base.Channel.Site_Content_SelectPageAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idResponse Site.Service.SiteService.SiteServices.ISiteService.Site_Content_SelectPageByc_id(Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idRequest request) {
            return base.Channel.Site_Content_SelectPageByc_id(request);
        }
        
        public System.Collections.Generic.List<Site.Service.SiteService.SiteServices.Site_Content> Site_Content_SelectPageByc_id(int cateId, int pageIndex, int pageSize, out int rowCount) {
            Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idRequest inValue = new Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idRequest();
            inValue.cateId = cateId;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idResponse retVal = ((Site.Service.SiteService.SiteServices.ISiteService)(this)).Site_Content_SelectPageByc_id(inValue);
            rowCount = retVal.rowCount;
            return retVal.Site_Content_SelectPageByc_idResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idResponse> Site_Content_SelectPageByc_idAsync(Site.Service.SiteService.SiteServices.Site_Content_SelectPageByc_idRequest request) {
            return base.Channel.Site_Content_SelectPageByc_idAsync(request);
        }
    }
}
