//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Service.SiteService.PublishPageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.jsonyang.com", ConfigurationName="PublishPageService.IPublishPageService")]
    public interface IPublishPageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IPublishPageService/PublishPage", ReplyAction="http://service.jsonyang.com/IPublishPageService/PublishPageResponse")]
        string PublishPage(string relationPath, string html);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IPublishPageService/PublishPage", ReplyAction="http://service.jsonyang.com/IPublishPageService/PublishPageResponse")]
        System.Threading.Tasks.Task<string> PublishPageAsync(string relationPath, string html);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublishPageServiceChannel : Site.Service.SiteService.PublishPageService.IPublishPageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublishPageServiceClient : System.ServiceModel.ClientBase<Site.Service.SiteService.PublishPageService.IPublishPageService>, Site.Service.SiteService.PublishPageService.IPublishPageService {
        
        public PublishPageServiceClient() {
        }
        
        public PublishPageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublishPageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishPageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishPageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PublishPage(string relationPath, string html) {
            return base.Channel.PublishPage(relationPath, html);
        }
        
        public System.Threading.Tasks.Task<string> PublishPageAsync(string relationPath, string html) {
            return base.Channel.PublishPageAsync(relationPath, html);
        }
    }
}
