//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Service.VideosService.VideosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VideoInfo", Namespace="http://schemas.datacontract.org/2004/07/Site.VideoModel")]
    [System.SerializableAttribute()]
    public partial class VideoInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int v_c_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string v_c_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string v_coverImgSrcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime v_createTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string v_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string v_introField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string v_min_playSrcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string v_playSrcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int v_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string v_timeLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string v_titileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int v_totalSecondField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int v_c_id {
            get {
                return this.v_c_idField;
            }
            set {
                if ((this.v_c_idField.Equals(value) != true)) {
                    this.v_c_idField = value;
                    this.RaisePropertyChanged("v_c_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string v_c_name {
            get {
                return this.v_c_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.v_c_nameField, value) != true)) {
                    this.v_c_nameField = value;
                    this.RaisePropertyChanged("v_c_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string v_coverImgSrc {
            get {
                return this.v_coverImgSrcField;
            }
            set {
                if ((object.ReferenceEquals(this.v_coverImgSrcField, value) != true)) {
                    this.v_coverImgSrcField = value;
                    this.RaisePropertyChanged("v_coverImgSrc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime v_createTime {
            get {
                return this.v_createTimeField;
            }
            set {
                if ((this.v_createTimeField.Equals(value) != true)) {
                    this.v_createTimeField = value;
                    this.RaisePropertyChanged("v_createTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string v_id {
            get {
                return this.v_idField;
            }
            set {
                if ((object.ReferenceEquals(this.v_idField, value) != true)) {
                    this.v_idField = value;
                    this.RaisePropertyChanged("v_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string v_intro {
            get {
                return this.v_introField;
            }
            set {
                if ((object.ReferenceEquals(this.v_introField, value) != true)) {
                    this.v_introField = value;
                    this.RaisePropertyChanged("v_intro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string v_min_playSrc {
            get {
                return this.v_min_playSrcField;
            }
            set {
                if ((object.ReferenceEquals(this.v_min_playSrcField, value) != true)) {
                    this.v_min_playSrcField = value;
                    this.RaisePropertyChanged("v_min_playSrc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string v_playSrc {
            get {
                return this.v_playSrcField;
            }
            set {
                if ((object.ReferenceEquals(this.v_playSrcField, value) != true)) {
                    this.v_playSrcField = value;
                    this.RaisePropertyChanged("v_playSrc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int v_status {
            get {
                return this.v_statusField;
            }
            set {
                if ((this.v_statusField.Equals(value) != true)) {
                    this.v_statusField = value;
                    this.RaisePropertyChanged("v_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string v_timeLength {
            get {
                return this.v_timeLengthField;
            }
            set {
                if ((object.ReferenceEquals(this.v_timeLengthField, value) != true)) {
                    this.v_timeLengthField = value;
                    this.RaisePropertyChanged("v_timeLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string v_titile {
            get {
                return this.v_titileField;
            }
            set {
                if ((object.ReferenceEquals(this.v_titileField, value) != true)) {
                    this.v_titileField = value;
                    this.RaisePropertyChanged("v_titile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int v_totalSecond {
            get {
                return this.v_totalSecondField;
            }
            set {
                if ((this.v_totalSecondField.Equals(value) != true)) {
                    this.v_totalSecondField = value;
                    this.RaisePropertyChanged("v_totalSecond");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VideoCate", Namespace="http://schemas.datacontract.org/2004/07/Site.VideoModel")]
    [System.SerializableAttribute()]
    public partial class VideoCate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_id {
            get {
                return this.c_idField;
            }
            set {
                if ((this.c_idField.Equals(value) != true)) {
                    this.c_idField = value;
                    this.RaisePropertyChanged("c_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_name {
            get {
                return this.c_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.c_nameField, value) != true)) {
                    this.c_nameField = value;
                    this.RaisePropertyChanged("c_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMailLog", Namespace="http://schemas.datacontract.org/2004/07/Site.VideoModel")]
    [System.SerializableAttribute()]
    public partial class SendMailLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendContent {
            get {
                return this.SendContentField;
            }
            set {
                if ((object.ReferenceEquals(this.SendContentField, value) != true)) {
                    this.SendContentField = value;
                    this.RaisePropertyChanged("SendContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendTime {
            get {
                return this.SendTimeField;
            }
            set {
                if ((this.SendTimeField.Equals(value) != true)) {
                    this.SendTimeField = value;
                    this.RaisePropertyChanged("SendTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComboInfo", Namespace="http://schemas.datacontract.org/2004/07/Site.VideoModel")]
    [System.SerializableAttribute()]
    public partial class ComboInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_daysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_introField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_numField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string c_titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_days {
            get {
                return this.c_daysField;
            }
            set {
                if ((this.c_daysField.Equals(value) != true)) {
                    this.c_daysField = value;
                    this.RaisePropertyChanged("c_days");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_id {
            get {
                return this.c_idField;
            }
            set {
                if ((object.ReferenceEquals(this.c_idField, value) != true)) {
                    this.c_idField = value;
                    this.RaisePropertyChanged("c_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_intro {
            get {
                return this.c_introField;
            }
            set {
                if ((object.ReferenceEquals(this.c_introField, value) != true)) {
                    this.c_introField = value;
                    this.RaisePropertyChanged("c_intro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_num {
            get {
                return this.c_numField;
            }
            set {
                if ((this.c_numField.Equals(value) != true)) {
                    this.c_numField = value;
                    this.RaisePropertyChanged("c_num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_status {
            get {
                return this.c_statusField;
            }
            set {
                if ((this.c_statusField.Equals(value) != true)) {
                    this.c_statusField = value;
                    this.RaisePropertyChanged("c_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c_title {
            get {
                return this.c_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.c_titleField, value) != true)) {
                    this.c_titleField = value;
                    this.RaisePropertyChanged("c_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.jsonyang.com", ConfigurationName="VideosService.IVideosService")]
    public interface IVideosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoInfo_Insert", ReplyAction="http://service.jsonyang.com/IVideosService/VideoInfo_InsertResponse")]
        int VideoInfo_Insert(Site.Service.VideosService.VideosService.VideoInfo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoInfo_Insert", ReplyAction="http://service.jsonyang.com/IVideosService/VideoInfo_InsertResponse")]
        System.Threading.Tasks.Task<int> VideoInfo_InsertAsync(Site.Service.VideosService.VideosService.VideoInfo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoInfo_DeleteById", ReplyAction="http://service.jsonyang.com/IVideosService/VideoInfo_DeleteByIdResponse")]
        int VideoInfo_DeleteById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoInfo_DeleteById", ReplyAction="http://service.jsonyang.com/IVideosService/VideoInfo_DeleteByIdResponse")]
        System.Threading.Tasks.Task<int> VideoInfo_DeleteByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoInfo_UpdateById", ReplyAction="http://service.jsonyang.com/IVideosService/VideoInfo_UpdateByIdResponse")]
        int VideoInfo_UpdateById(Site.Service.VideosService.VideosService.VideoInfo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoInfo_UpdateById", ReplyAction="http://service.jsonyang.com/IVideosService/VideoInfo_UpdateByIdResponse")]
        System.Threading.Tasks.Task<int> VideoInfo_UpdateByIdAsync(Site.Service.VideosService.VideosService.VideoInfo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoInfo_SelectPage", ReplyAction="http://service.jsonyang.com/IVideosService/VideoInfo_SelectPageResponse")]
        Site.Service.VideosService.VideosService.VideoInfo_SelectPageResponse VideoInfo_SelectPage(Site.Service.VideosService.VideosService.VideoInfo_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoInfo_SelectPage", ReplyAction="http://service.jsonyang.com/IVideosService/VideoInfo_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.VideoInfo_SelectPageResponse> VideoInfo_SelectPageAsync(Site.Service.VideosService.VideosService.VideoInfo_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoInfo_SelectById", ReplyAction="http://service.jsonyang.com/IVideosService/VideoInfo_SelectByIdResponse")]
        Site.Service.VideosService.VideosService.VideoInfo VideoInfo_SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoInfo_SelectById", ReplyAction="http://service.jsonyang.com/IVideosService/VideoInfo_SelectByIdResponse")]
        System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.VideoInfo> VideoInfo_SelectByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoCate_Insert", ReplyAction="http://service.jsonyang.com/IVideosService/VideoCate_InsertResponse")]
        int VideoCate_Insert(Site.Service.VideosService.VideosService.VideoCate obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoCate_Insert", ReplyAction="http://service.jsonyang.com/IVideosService/VideoCate_InsertResponse")]
        System.Threading.Tasks.Task<int> VideoCate_InsertAsync(Site.Service.VideosService.VideosService.VideoCate obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoCate_DeleteByc_id", ReplyAction="http://service.jsonyang.com/IVideosService/VideoCate_DeleteByc_idResponse")]
        int VideoCate_DeleteByc_id(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoCate_DeleteByc_id", ReplyAction="http://service.jsonyang.com/IVideosService/VideoCate_DeleteByc_idResponse")]
        System.Threading.Tasks.Task<int> VideoCate_DeleteByc_idAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoCate_UpdateByc_id", ReplyAction="http://service.jsonyang.com/IVideosService/VideoCate_UpdateByc_idResponse")]
        int VideoCate_UpdateByc_id(Site.Service.VideosService.VideosService.VideoCate obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoCate_UpdateByc_id", ReplyAction="http://service.jsonyang.com/IVideosService/VideoCate_UpdateByc_idResponse")]
        System.Threading.Tasks.Task<int> VideoCate_UpdateByc_idAsync(Site.Service.VideosService.VideosService.VideoCate obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoCate_SelectPage", ReplyAction="http://service.jsonyang.com/IVideosService/VideoCate_SelectPageResponse")]
        Site.Service.VideosService.VideosService.VideoCate_SelectPageResponse VideoCate_SelectPage(Site.Service.VideosService.VideosService.VideoCate_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoCate_SelectPage", ReplyAction="http://service.jsonyang.com/IVideosService/VideoCate_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.VideoCate_SelectPageResponse> VideoCate_SelectPageAsync(Site.Service.VideosService.VideosService.VideoCate_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoCate_SelectByc_id", ReplyAction="http://service.jsonyang.com/IVideosService/VideoCate_SelectByc_idResponse")]
        Site.Service.VideosService.VideosService.VideoCate VideoCate_SelectByc_id(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/VideoCate_SelectByc_id", ReplyAction="http://service.jsonyang.com/IVideosService/VideoCate_SelectByc_idResponse")]
        System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.VideoCate> VideoCate_SelectByc_idAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/SendMailLog_Insert", ReplyAction="http://service.jsonyang.com/IVideosService/SendMailLog_InsertResponse")]
        int SendMailLog_Insert(Site.Service.VideosService.VideosService.SendMailLog obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/SendMailLog_Insert", ReplyAction="http://service.jsonyang.com/IVideosService/SendMailLog_InsertResponse")]
        System.Threading.Tasks.Task<int> SendMailLog_InsertAsync(Site.Service.VideosService.VideosService.SendMailLog obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/SendMailLog_DeleteById", ReplyAction="http://service.jsonyang.com/IVideosService/SendMailLog_DeleteByIdResponse")]
        int SendMailLog_DeleteById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/SendMailLog_DeleteById", ReplyAction="http://service.jsonyang.com/IVideosService/SendMailLog_DeleteByIdResponse")]
        System.Threading.Tasks.Task<int> SendMailLog_DeleteByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/SendMailLog_UpdateById", ReplyAction="http://service.jsonyang.com/IVideosService/SendMailLog_UpdateByIdResponse")]
        int SendMailLog_UpdateById(Site.Service.VideosService.VideosService.SendMailLog obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/SendMailLog_UpdateById", ReplyAction="http://service.jsonyang.com/IVideosService/SendMailLog_UpdateByIdResponse")]
        System.Threading.Tasks.Task<int> SendMailLog_UpdateByIdAsync(Site.Service.VideosService.VideosService.SendMailLog obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/SendMailLog_SelectPage", ReplyAction="http://service.jsonyang.com/IVideosService/SendMailLog_SelectPageResponse")]
        Site.Service.VideosService.VideosService.SendMailLog_SelectPageResponse SendMailLog_SelectPage(Site.Service.VideosService.VideosService.SendMailLog_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/SendMailLog_SelectPage", ReplyAction="http://service.jsonyang.com/IVideosService/SendMailLog_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.SendMailLog_SelectPageResponse> SendMailLog_SelectPageAsync(Site.Service.VideosService.VideosService.SendMailLog_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/SendMailLog_SelectById", ReplyAction="http://service.jsonyang.com/IVideosService/SendMailLog_SelectByIdResponse")]
        Site.Service.VideosService.VideosService.SendMailLog SendMailLog_SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/SendMailLog_SelectById", ReplyAction="http://service.jsonyang.com/IVideosService/SendMailLog_SelectByIdResponse")]
        System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.SendMailLog> SendMailLog_SelectByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_Insert", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_InsertResponse")]
        int ComboInfo_Insert(Site.Service.VideosService.VideosService.ComboInfo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_Insert", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_InsertResponse")]
        System.Threading.Tasks.Task<int> ComboInfo_InsertAsync(Site.Service.VideosService.VideosService.ComboInfo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_DeleteById", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_DeleteByIdResponse")]
        int ComboInfo_DeleteById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_DeleteById", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_DeleteByIdResponse")]
        System.Threading.Tasks.Task<int> ComboInfo_DeleteByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_UpdateById", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_UpdateByIdResponse")]
        int ComboInfo_UpdateById(Site.Service.VideosService.VideosService.ComboInfo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_UpdateById", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_UpdateByIdResponse")]
        System.Threading.Tasks.Task<int> ComboInfo_UpdateByIdAsync(Site.Service.VideosService.VideosService.ComboInfo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_SelectPage", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_SelectPageResponse")]
        Site.Service.VideosService.VideosService.ComboInfo_SelectPageResponse ComboInfo_SelectPage(Site.Service.VideosService.VideosService.ComboInfo_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_SelectPage", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.ComboInfo_SelectPageResponse> ComboInfo_SelectPageAsync(Site.Service.VideosService.VideosService.ComboInfo_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_SelectById", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_SelectByIdResponse")]
        Site.Service.VideosService.VideosService.ComboInfo ComboInfo_SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_SelectById", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_SelectByIdResponse")]
        System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.ComboInfo> ComboInfo_SelectByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_SelectByc_id", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_SelectByc_idResponse")]
        Site.Service.VideosService.VideosService.ComboInfo ComboInfo_SelectByc_id(string c_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IVideosService/ComboInfo_SelectByc_id", ReplyAction="http://service.jsonyang.com/IVideosService/ComboInfo_SelectByc_idResponse")]
        System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.ComboInfo> ComboInfo_SelectByc_idAsync(string c_id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VideoInfo_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class VideoInfo_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public string where;
        
        public VideoInfo_SelectPageRequest() {
        }
        
        public VideoInfo_SelectPageRequest(string cloumns, int pageIndex, int pageSize, string orderBy, string where) {
            this.cloumns = cloumns;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderBy = orderBy;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VideoInfo_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class VideoInfo_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.VideosService.VideosService.VideoInfo> VideoInfo_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public VideoInfo_SelectPageResponse() {
        }
        
        public VideoInfo_SelectPageResponse(System.Collections.Generic.List<Site.Service.VideosService.VideosService.VideoInfo> VideoInfo_SelectPageResult, int rowCount) {
            this.VideoInfo_SelectPageResult = VideoInfo_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VideoCate_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class VideoCate_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public string where;
        
        public VideoCate_SelectPageRequest() {
        }
        
        public VideoCate_SelectPageRequest(string cloumns, int pageIndex, int pageSize, string orderBy, string where) {
            this.cloumns = cloumns;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderBy = orderBy;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VideoCate_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class VideoCate_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.VideosService.VideosService.VideoCate> VideoCate_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public VideoCate_SelectPageResponse() {
        }
        
        public VideoCate_SelectPageResponse(System.Collections.Generic.List<Site.Service.VideosService.VideosService.VideoCate> VideoCate_SelectPageResult, int rowCount) {
            this.VideoCate_SelectPageResult = VideoCate_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMailLog_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class SendMailLog_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public string where;
        
        public SendMailLog_SelectPageRequest() {
        }
        
        public SendMailLog_SelectPageRequest(string cloumns, int pageIndex, int pageSize, string orderBy, string where) {
            this.cloumns = cloumns;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderBy = orderBy;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMailLog_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class SendMailLog_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.VideosService.VideosService.SendMailLog> SendMailLog_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public SendMailLog_SelectPageResponse() {
        }
        
        public SendMailLog_SelectPageResponse(System.Collections.Generic.List<Site.Service.VideosService.VideosService.SendMailLog> SendMailLog_SelectPageResult, int rowCount) {
            this.SendMailLog_SelectPageResult = SendMailLog_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComboInfo_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class ComboInfo_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public string where;
        
        public ComboInfo_SelectPageRequest() {
        }
        
        public ComboInfo_SelectPageRequest(string cloumns, int pageIndex, int pageSize, string orderBy, string where) {
            this.cloumns = cloumns;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderBy = orderBy;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComboInfo_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class ComboInfo_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.VideosService.VideosService.ComboInfo> ComboInfo_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public ComboInfo_SelectPageResponse() {
        }
        
        public ComboInfo_SelectPageResponse(System.Collections.Generic.List<Site.Service.VideosService.VideosService.ComboInfo> ComboInfo_SelectPageResult, int rowCount) {
            this.ComboInfo_SelectPageResult = ComboInfo_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVideosServiceChannel : Site.Service.VideosService.VideosService.IVideosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VideosServiceClient : System.ServiceModel.ClientBase<Site.Service.VideosService.VideosService.IVideosService>, Site.Service.VideosService.VideosService.IVideosService {
        
        public VideosServiceClient() {
        }
        
        public VideosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VideosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VideosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VideosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int VideoInfo_Insert(Site.Service.VideosService.VideosService.VideoInfo obj) {
            return base.Channel.VideoInfo_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> VideoInfo_InsertAsync(Site.Service.VideosService.VideosService.VideoInfo obj) {
            return base.Channel.VideoInfo_InsertAsync(obj);
        }
        
        public int VideoInfo_DeleteById(int Id) {
            return base.Channel.VideoInfo_DeleteById(Id);
        }
        
        public System.Threading.Tasks.Task<int> VideoInfo_DeleteByIdAsync(int Id) {
            return base.Channel.VideoInfo_DeleteByIdAsync(Id);
        }
        
        public int VideoInfo_UpdateById(Site.Service.VideosService.VideosService.VideoInfo obj) {
            return base.Channel.VideoInfo_UpdateById(obj);
        }
        
        public System.Threading.Tasks.Task<int> VideoInfo_UpdateByIdAsync(Site.Service.VideosService.VideosService.VideoInfo obj) {
            return base.Channel.VideoInfo_UpdateByIdAsync(obj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.VideosService.VideosService.VideoInfo_SelectPageResponse Site.Service.VideosService.VideosService.IVideosService.VideoInfo_SelectPage(Site.Service.VideosService.VideosService.VideoInfo_SelectPageRequest request) {
            return base.Channel.VideoInfo_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.VideosService.VideosService.VideoInfo> VideoInfo_SelectPage(string cloumns, int pageIndex, int pageSize, string orderBy, string where, out int rowCount) {
            Site.Service.VideosService.VideosService.VideoInfo_SelectPageRequest inValue = new Site.Service.VideosService.VideosService.VideoInfo_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderBy = orderBy;
            inValue.where = where;
            Site.Service.VideosService.VideosService.VideoInfo_SelectPageResponse retVal = ((Site.Service.VideosService.VideosService.IVideosService)(this)).VideoInfo_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.VideoInfo_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.VideoInfo_SelectPageResponse> VideoInfo_SelectPageAsync(Site.Service.VideosService.VideosService.VideoInfo_SelectPageRequest request) {
            return base.Channel.VideoInfo_SelectPageAsync(request);
        }
        
        public Site.Service.VideosService.VideosService.VideoInfo VideoInfo_SelectById(int Id) {
            return base.Channel.VideoInfo_SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.VideoInfo> VideoInfo_SelectByIdAsync(int Id) {
            return base.Channel.VideoInfo_SelectByIdAsync(Id);
        }
        
        public int VideoCate_Insert(Site.Service.VideosService.VideosService.VideoCate obj) {
            return base.Channel.VideoCate_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> VideoCate_InsertAsync(Site.Service.VideosService.VideosService.VideoCate obj) {
            return base.Channel.VideoCate_InsertAsync(obj);
        }
        
        public int VideoCate_DeleteByc_id(int Id) {
            return base.Channel.VideoCate_DeleteByc_id(Id);
        }
        
        public System.Threading.Tasks.Task<int> VideoCate_DeleteByc_idAsync(int Id) {
            return base.Channel.VideoCate_DeleteByc_idAsync(Id);
        }
        
        public int VideoCate_UpdateByc_id(Site.Service.VideosService.VideosService.VideoCate obj) {
            return base.Channel.VideoCate_UpdateByc_id(obj);
        }
        
        public System.Threading.Tasks.Task<int> VideoCate_UpdateByc_idAsync(Site.Service.VideosService.VideosService.VideoCate obj) {
            return base.Channel.VideoCate_UpdateByc_idAsync(obj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.VideosService.VideosService.VideoCate_SelectPageResponse Site.Service.VideosService.VideosService.IVideosService.VideoCate_SelectPage(Site.Service.VideosService.VideosService.VideoCate_SelectPageRequest request) {
            return base.Channel.VideoCate_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.VideosService.VideosService.VideoCate> VideoCate_SelectPage(string cloumns, int pageIndex, int pageSize, string orderBy, string where, out int rowCount) {
            Site.Service.VideosService.VideosService.VideoCate_SelectPageRequest inValue = new Site.Service.VideosService.VideosService.VideoCate_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderBy = orderBy;
            inValue.where = where;
            Site.Service.VideosService.VideosService.VideoCate_SelectPageResponse retVal = ((Site.Service.VideosService.VideosService.IVideosService)(this)).VideoCate_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.VideoCate_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.VideoCate_SelectPageResponse> VideoCate_SelectPageAsync(Site.Service.VideosService.VideosService.VideoCate_SelectPageRequest request) {
            return base.Channel.VideoCate_SelectPageAsync(request);
        }
        
        public Site.Service.VideosService.VideosService.VideoCate VideoCate_SelectByc_id(int Id) {
            return base.Channel.VideoCate_SelectByc_id(Id);
        }
        
        public System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.VideoCate> VideoCate_SelectByc_idAsync(int Id) {
            return base.Channel.VideoCate_SelectByc_idAsync(Id);
        }
        
        public int SendMailLog_Insert(Site.Service.VideosService.VideosService.SendMailLog obj) {
            return base.Channel.SendMailLog_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> SendMailLog_InsertAsync(Site.Service.VideosService.VideosService.SendMailLog obj) {
            return base.Channel.SendMailLog_InsertAsync(obj);
        }
        
        public int SendMailLog_DeleteById(int Id) {
            return base.Channel.SendMailLog_DeleteById(Id);
        }
        
        public System.Threading.Tasks.Task<int> SendMailLog_DeleteByIdAsync(int Id) {
            return base.Channel.SendMailLog_DeleteByIdAsync(Id);
        }
        
        public int SendMailLog_UpdateById(Site.Service.VideosService.VideosService.SendMailLog obj) {
            return base.Channel.SendMailLog_UpdateById(obj);
        }
        
        public System.Threading.Tasks.Task<int> SendMailLog_UpdateByIdAsync(Site.Service.VideosService.VideosService.SendMailLog obj) {
            return base.Channel.SendMailLog_UpdateByIdAsync(obj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.VideosService.VideosService.SendMailLog_SelectPageResponse Site.Service.VideosService.VideosService.IVideosService.SendMailLog_SelectPage(Site.Service.VideosService.VideosService.SendMailLog_SelectPageRequest request) {
            return base.Channel.SendMailLog_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.VideosService.VideosService.SendMailLog> SendMailLog_SelectPage(string cloumns, int pageIndex, int pageSize, string orderBy, string where, out int rowCount) {
            Site.Service.VideosService.VideosService.SendMailLog_SelectPageRequest inValue = new Site.Service.VideosService.VideosService.SendMailLog_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderBy = orderBy;
            inValue.where = where;
            Site.Service.VideosService.VideosService.SendMailLog_SelectPageResponse retVal = ((Site.Service.VideosService.VideosService.IVideosService)(this)).SendMailLog_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.SendMailLog_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.SendMailLog_SelectPageResponse> SendMailLog_SelectPageAsync(Site.Service.VideosService.VideosService.SendMailLog_SelectPageRequest request) {
            return base.Channel.SendMailLog_SelectPageAsync(request);
        }
        
        public Site.Service.VideosService.VideosService.SendMailLog SendMailLog_SelectById(int Id) {
            return base.Channel.SendMailLog_SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.SendMailLog> SendMailLog_SelectByIdAsync(int Id) {
            return base.Channel.SendMailLog_SelectByIdAsync(Id);
        }
        
        public int ComboInfo_Insert(Site.Service.VideosService.VideosService.ComboInfo obj) {
            return base.Channel.ComboInfo_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> ComboInfo_InsertAsync(Site.Service.VideosService.VideosService.ComboInfo obj) {
            return base.Channel.ComboInfo_InsertAsync(obj);
        }
        
        public int ComboInfo_DeleteById(int Id) {
            return base.Channel.ComboInfo_DeleteById(Id);
        }
        
        public System.Threading.Tasks.Task<int> ComboInfo_DeleteByIdAsync(int Id) {
            return base.Channel.ComboInfo_DeleteByIdAsync(Id);
        }
        
        public int ComboInfo_UpdateById(Site.Service.VideosService.VideosService.ComboInfo obj) {
            return base.Channel.ComboInfo_UpdateById(obj);
        }
        
        public System.Threading.Tasks.Task<int> ComboInfo_UpdateByIdAsync(Site.Service.VideosService.VideosService.ComboInfo obj) {
            return base.Channel.ComboInfo_UpdateByIdAsync(obj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.VideosService.VideosService.ComboInfo_SelectPageResponse Site.Service.VideosService.VideosService.IVideosService.ComboInfo_SelectPage(Site.Service.VideosService.VideosService.ComboInfo_SelectPageRequest request) {
            return base.Channel.ComboInfo_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.VideosService.VideosService.ComboInfo> ComboInfo_SelectPage(string cloumns, int pageIndex, int pageSize, string orderBy, string where, out int rowCount) {
            Site.Service.VideosService.VideosService.ComboInfo_SelectPageRequest inValue = new Site.Service.VideosService.VideosService.ComboInfo_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderBy = orderBy;
            inValue.where = where;
            Site.Service.VideosService.VideosService.ComboInfo_SelectPageResponse retVal = ((Site.Service.VideosService.VideosService.IVideosService)(this)).ComboInfo_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.ComboInfo_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.ComboInfo_SelectPageResponse> ComboInfo_SelectPageAsync(Site.Service.VideosService.VideosService.ComboInfo_SelectPageRequest request) {
            return base.Channel.ComboInfo_SelectPageAsync(request);
        }
        
        public Site.Service.VideosService.VideosService.ComboInfo ComboInfo_SelectById(int Id) {
            return base.Channel.ComboInfo_SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.ComboInfo> ComboInfo_SelectByIdAsync(int Id) {
            return base.Channel.ComboInfo_SelectByIdAsync(Id);
        }
        
        public Site.Service.VideosService.VideosService.ComboInfo ComboInfo_SelectByc_id(string c_id) {
            return base.Channel.ComboInfo_SelectByc_id(c_id);
        }
        
        public System.Threading.Tasks.Task<Site.Service.VideosService.VideosService.ComboInfo> ComboInfo_SelectByc_idAsync(string c_id) {
            return base.Channel.ComboInfo_SelectByc_idAsync(c_id);
        }
    }
}
