//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Service.YuYangService.YuYangServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fiction", Namespace="http://schemas.datacontract.org/2004/07/Site.YuYangModel")]
    [System.SerializableAttribute()]
    public partial class Fiction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int C_C_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompleteStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoverImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastChapterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdateChapterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int C_C_ID {
            get {
                return this.C_C_IDField;
            }
            set {
                if ((this.C_C_IDField.Equals(value) != true)) {
                    this.C_C_IDField = value;
                    this.RaisePropertyChanged("C_C_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompleteState {
            get {
                return this.CompleteStateField;
            }
            set {
                if ((this.CompleteStateField.Equals(value) != true)) {
                    this.CompleteStateField = value;
                    this.RaisePropertyChanged("CompleteState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoverImage {
            get {
                return this.CoverImageField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverImageField, value) != true)) {
                    this.CoverImageField = value;
                    this.RaisePropertyChanged("CoverImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Intro {
            get {
                return this.IntroField;
            }
            set {
                if ((object.ReferenceEquals(this.IntroField, value) != true)) {
                    this.IntroField = value;
                    this.RaisePropertyChanged("Intro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastChapterId {
            get {
                return this.LastChapterIdField;
            }
            set {
                if ((this.LastChapterIdField.Equals(value) != true)) {
                    this.LastChapterIdField = value;
                    this.RaisePropertyChanged("LastChapterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdateChapter {
            get {
                return this.LastUpdateChapterField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdateChapterField, value) != true)) {
                    this.LastUpdateChapterField = value;
                    this.RaisePropertyChanged("LastUpdateChapter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateTime {
            get {
                return this.LastUpdateTimeField;
            }
            set {
                if ((this.LastUpdateTimeField.Equals(value) != true)) {
                    this.LastUpdateTimeField = value;
                    this.RaisePropertyChanged("LastUpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentCate", Namespace="http://schemas.datacontract.org/2004/07/Site.YuYangModel")]
    [System.SerializableAttribute()]
    public partial class ContentCate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CateName {
            get {
                return this.CateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CateNameField, value) != true)) {
                    this.CateNameField = value;
                    this.RaisePropertyChanged("CateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChapterVisits", Namespace="http://schemas.datacontract.org/2004/07/Site.YuYangModel")]
    [System.SerializableAttribute()]
    public partial class ChapterVisits : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrowserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Browser {
            get {
                return this.BrowserField;
            }
            set {
                if ((object.ReferenceEquals(this.BrowserField, value) != true)) {
                    this.BrowserField = value;
                    this.RaisePropertyChanged("Browser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OS {
            get {
                return this.OSField;
            }
            set {
                if ((object.ReferenceEquals(this.OSField, value) != true)) {
                    this.OSField = value;
                    this.RaisePropertyChanged("OS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.jsonyang.com", ConfigurationName="YuYangServices.IYuYangService")]
    public interface IYuYangService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/Fiction_Insert", ReplyAction="http://service.jsonyang.com/IYuYangService/Fiction_InsertResponse")]
        int Fiction_Insert(Site.Service.YuYangService.YuYangServices.Fiction obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/Fiction_Insert", ReplyAction="http://service.jsonyang.com/IYuYangService/Fiction_InsertResponse")]
        System.Threading.Tasks.Task<int> Fiction_InsertAsync(Site.Service.YuYangService.YuYangServices.Fiction obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/Fiction_DeleteById", ReplyAction="http://service.jsonyang.com/IYuYangService/Fiction_DeleteByIdResponse")]
        int Fiction_DeleteById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/Fiction_DeleteById", ReplyAction="http://service.jsonyang.com/IYuYangService/Fiction_DeleteByIdResponse")]
        System.Threading.Tasks.Task<int> Fiction_DeleteByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/Fiction_UpdateById", ReplyAction="http://service.jsonyang.com/IYuYangService/Fiction_UpdateByIdResponse")]
        int Fiction_UpdateById(Site.Service.YuYangService.YuYangServices.Fiction obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/Fiction_UpdateById", ReplyAction="http://service.jsonyang.com/IYuYangService/Fiction_UpdateByIdResponse")]
        System.Threading.Tasks.Task<int> Fiction_UpdateByIdAsync(Site.Service.YuYangService.YuYangServices.Fiction obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/Fiction_SelectById", ReplyAction="http://service.jsonyang.com/IYuYangService/Fiction_SelectByIdResponse")]
        Site.Service.YuYangService.YuYangServices.Fiction Fiction_SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/Fiction_SelectById", ReplyAction="http://service.jsonyang.com/IYuYangService/Fiction_SelectByIdResponse")]
        System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.Fiction> Fiction_SelectByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/Fiction_SelectPage", ReplyAction="http://service.jsonyang.com/IYuYangService/Fiction_SelectPageResponse")]
        Site.Service.YuYangService.YuYangServices.Fiction_SelectPageResponse Fiction_SelectPage(Site.Service.YuYangService.YuYangServices.Fiction_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/Fiction_SelectPage", ReplyAction="http://service.jsonyang.com/IYuYangService/Fiction_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.Fiction_SelectPageResponse> Fiction_SelectPageAsync(Site.Service.YuYangService.YuYangServices.Fiction_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ContentCate_Insert", ReplyAction="http://service.jsonyang.com/IYuYangService/ContentCate_InsertResponse")]
        int ContentCate_Insert(Site.Service.YuYangService.YuYangServices.ContentCate obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ContentCate_Insert", ReplyAction="http://service.jsonyang.com/IYuYangService/ContentCate_InsertResponse")]
        System.Threading.Tasks.Task<int> ContentCate_InsertAsync(Site.Service.YuYangService.YuYangServices.ContentCate obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ContentCate_DeleteById", ReplyAction="http://service.jsonyang.com/IYuYangService/ContentCate_DeleteByIdResponse")]
        int ContentCate_DeleteById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ContentCate_DeleteById", ReplyAction="http://service.jsonyang.com/IYuYangService/ContentCate_DeleteByIdResponse")]
        System.Threading.Tasks.Task<int> ContentCate_DeleteByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ContentCate_UpdateById", ReplyAction="http://service.jsonyang.com/IYuYangService/ContentCate_UpdateByIdResponse")]
        int ContentCate_UpdateById(Site.Service.YuYangService.YuYangServices.ContentCate obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ContentCate_UpdateById", ReplyAction="http://service.jsonyang.com/IYuYangService/ContentCate_UpdateByIdResponse")]
        System.Threading.Tasks.Task<int> ContentCate_UpdateByIdAsync(Site.Service.YuYangService.YuYangServices.ContentCate obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ContentCate_SelectById", ReplyAction="http://service.jsonyang.com/IYuYangService/ContentCate_SelectByIdResponse")]
        Site.Service.YuYangService.YuYangServices.ContentCate ContentCate_SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ContentCate_SelectById", ReplyAction="http://service.jsonyang.com/IYuYangService/ContentCate_SelectByIdResponse")]
        System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.ContentCate> ContentCate_SelectByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ContentCate_SelectPage", ReplyAction="http://service.jsonyang.com/IYuYangService/ContentCate_SelectPageResponse")]
        Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageResponse ContentCate_SelectPage(Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ContentCate_SelectPage", ReplyAction="http://service.jsonyang.com/IYuYangService/ContentCate_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageResponse> ContentCate_SelectPageAsync(Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ChapterVisits_Insert", ReplyAction="http://service.jsonyang.com/IYuYangService/ChapterVisits_InsertResponse")]
        int ChapterVisits_Insert(Site.Service.YuYangService.YuYangServices.ChapterVisits obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ChapterVisits_Insert", ReplyAction="http://service.jsonyang.com/IYuYangService/ChapterVisits_InsertResponse")]
        System.Threading.Tasks.Task<int> ChapterVisits_InsertAsync(Site.Service.YuYangService.YuYangServices.ChapterVisits obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ChapterVisits_DeleteById", ReplyAction="http://service.jsonyang.com/IYuYangService/ChapterVisits_DeleteByIdResponse")]
        int ChapterVisits_DeleteById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ChapterVisits_DeleteById", ReplyAction="http://service.jsonyang.com/IYuYangService/ChapterVisits_DeleteByIdResponse")]
        System.Threading.Tasks.Task<int> ChapterVisits_DeleteByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ChapterVisits_UpdateById", ReplyAction="http://service.jsonyang.com/IYuYangService/ChapterVisits_UpdateByIdResponse")]
        int ChapterVisits_UpdateById(Site.Service.YuYangService.YuYangServices.ChapterVisits obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ChapterVisits_UpdateById", ReplyAction="http://service.jsonyang.com/IYuYangService/ChapterVisits_UpdateByIdResponse")]
        System.Threading.Tasks.Task<int> ChapterVisits_UpdateByIdAsync(Site.Service.YuYangService.YuYangServices.ChapterVisits obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ChapterVisits_SelectById", ReplyAction="http://service.jsonyang.com/IYuYangService/ChapterVisits_SelectByIdResponse")]
        Site.Service.YuYangService.YuYangServices.ChapterVisits ChapterVisits_SelectById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ChapterVisits_SelectById", ReplyAction="http://service.jsonyang.com/IYuYangService/ChapterVisits_SelectByIdResponse")]
        System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.ChapterVisits> ChapterVisits_SelectByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ChapterVisits_SelectPage", ReplyAction="http://service.jsonyang.com/IYuYangService/ChapterVisits_SelectPageResponse")]
        Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageResponse ChapterVisits_SelectPage(Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://service.jsonyang.com/IYuYangService/ChapterVisits_SelectPage", ReplyAction="http://service.jsonyang.com/IYuYangService/ChapterVisits_SelectPageResponse")]
        System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageResponse> ChapterVisits_SelectPageAsync(Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fiction_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Fiction_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public string where;
        
        public Fiction_SelectPageRequest() {
        }
        
        public Fiction_SelectPageRequest(string cloumns, int pageIndex, int pageSize, string orderBy, string where) {
            this.cloumns = cloumns;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderBy = orderBy;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fiction_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class Fiction_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.YuYangService.YuYangServices.Fiction> Fiction_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public Fiction_SelectPageResponse() {
        }
        
        public Fiction_SelectPageResponse(System.Collections.Generic.List<Site.Service.YuYangService.YuYangServices.Fiction> Fiction_SelectPageResult, int rowCount) {
            this.Fiction_SelectPageResult = Fiction_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ContentCate_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class ContentCate_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public string where;
        
        public ContentCate_SelectPageRequest() {
        }
        
        public ContentCate_SelectPageRequest(string cloumns, int pageIndex, int pageSize, string orderBy, string where) {
            this.cloumns = cloumns;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderBy = orderBy;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ContentCate_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class ContentCate_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.YuYangService.YuYangServices.ContentCate> ContentCate_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public ContentCate_SelectPageResponse() {
        }
        
        public ContentCate_SelectPageResponse(System.Collections.Generic.List<Site.Service.YuYangService.YuYangServices.ContentCate> ContentCate_SelectPageResult, int rowCount) {
            this.ContentCate_SelectPageResult = ContentCate_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChapterVisits_SelectPage", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class ChapterVisits_SelectPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public string cloumns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=2)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=3)]
        public string orderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=4)]
        public string where;
        
        public ChapterVisits_SelectPageRequest() {
        }
        
        public ChapterVisits_SelectPageRequest(string cloumns, int pageIndex, int pageSize, string orderBy, string where) {
            this.cloumns = cloumns;
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderBy = orderBy;
            this.where = where;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChapterVisits_SelectPageResponse", WrapperNamespace="http://service.jsonyang.com", IsWrapped=true)]
    public partial class ChapterVisits_SelectPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=0)]
        public System.Collections.Generic.List<Site.Service.YuYangService.YuYangServices.ChapterVisits> ChapterVisits_SelectPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.jsonyang.com", Order=1)]
        public int rowCount;
        
        public ChapterVisits_SelectPageResponse() {
        }
        
        public ChapterVisits_SelectPageResponse(System.Collections.Generic.List<Site.Service.YuYangService.YuYangServices.ChapterVisits> ChapterVisits_SelectPageResult, int rowCount) {
            this.ChapterVisits_SelectPageResult = ChapterVisits_SelectPageResult;
            this.rowCount = rowCount;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IYuYangServiceChannel : Site.Service.YuYangService.YuYangServices.IYuYangService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YuYangServiceClient : System.ServiceModel.ClientBase<Site.Service.YuYangService.YuYangServices.IYuYangService>, Site.Service.YuYangService.YuYangServices.IYuYangService {
        
        public YuYangServiceClient() {
        }
        
        public YuYangServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YuYangServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YuYangServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YuYangServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Fiction_Insert(Site.Service.YuYangService.YuYangServices.Fiction obj) {
            return base.Channel.Fiction_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> Fiction_InsertAsync(Site.Service.YuYangService.YuYangServices.Fiction obj) {
            return base.Channel.Fiction_InsertAsync(obj);
        }
        
        public int Fiction_DeleteById(int Id) {
            return base.Channel.Fiction_DeleteById(Id);
        }
        
        public System.Threading.Tasks.Task<int> Fiction_DeleteByIdAsync(int Id) {
            return base.Channel.Fiction_DeleteByIdAsync(Id);
        }
        
        public int Fiction_UpdateById(Site.Service.YuYangService.YuYangServices.Fiction obj) {
            return base.Channel.Fiction_UpdateById(obj);
        }
        
        public System.Threading.Tasks.Task<int> Fiction_UpdateByIdAsync(Site.Service.YuYangService.YuYangServices.Fiction obj) {
            return base.Channel.Fiction_UpdateByIdAsync(obj);
        }
        
        public Site.Service.YuYangService.YuYangServices.Fiction Fiction_SelectById(int Id) {
            return base.Channel.Fiction_SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.Fiction> Fiction_SelectByIdAsync(int Id) {
            return base.Channel.Fiction_SelectByIdAsync(Id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.YuYangService.YuYangServices.Fiction_SelectPageResponse Site.Service.YuYangService.YuYangServices.IYuYangService.Fiction_SelectPage(Site.Service.YuYangService.YuYangServices.Fiction_SelectPageRequest request) {
            return base.Channel.Fiction_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.YuYangService.YuYangServices.Fiction> Fiction_SelectPage(string cloumns, int pageIndex, int pageSize, string orderBy, string where, out int rowCount) {
            Site.Service.YuYangService.YuYangServices.Fiction_SelectPageRequest inValue = new Site.Service.YuYangService.YuYangServices.Fiction_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderBy = orderBy;
            inValue.where = where;
            Site.Service.YuYangService.YuYangServices.Fiction_SelectPageResponse retVal = ((Site.Service.YuYangService.YuYangServices.IYuYangService)(this)).Fiction_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.Fiction_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.Fiction_SelectPageResponse> Fiction_SelectPageAsync(Site.Service.YuYangService.YuYangServices.Fiction_SelectPageRequest request) {
            return base.Channel.Fiction_SelectPageAsync(request);
        }
        
        public int ContentCate_Insert(Site.Service.YuYangService.YuYangServices.ContentCate obj) {
            return base.Channel.ContentCate_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> ContentCate_InsertAsync(Site.Service.YuYangService.YuYangServices.ContentCate obj) {
            return base.Channel.ContentCate_InsertAsync(obj);
        }
        
        public int ContentCate_DeleteById(int Id) {
            return base.Channel.ContentCate_DeleteById(Id);
        }
        
        public System.Threading.Tasks.Task<int> ContentCate_DeleteByIdAsync(int Id) {
            return base.Channel.ContentCate_DeleteByIdAsync(Id);
        }
        
        public int ContentCate_UpdateById(Site.Service.YuYangService.YuYangServices.ContentCate obj) {
            return base.Channel.ContentCate_UpdateById(obj);
        }
        
        public System.Threading.Tasks.Task<int> ContentCate_UpdateByIdAsync(Site.Service.YuYangService.YuYangServices.ContentCate obj) {
            return base.Channel.ContentCate_UpdateByIdAsync(obj);
        }
        
        public Site.Service.YuYangService.YuYangServices.ContentCate ContentCate_SelectById(int Id) {
            return base.Channel.ContentCate_SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.ContentCate> ContentCate_SelectByIdAsync(int Id) {
            return base.Channel.ContentCate_SelectByIdAsync(Id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageResponse Site.Service.YuYangService.YuYangServices.IYuYangService.ContentCate_SelectPage(Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageRequest request) {
            return base.Channel.ContentCate_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.YuYangService.YuYangServices.ContentCate> ContentCate_SelectPage(string cloumns, int pageIndex, int pageSize, string orderBy, string where, out int rowCount) {
            Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageRequest inValue = new Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderBy = orderBy;
            inValue.where = where;
            Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageResponse retVal = ((Site.Service.YuYangService.YuYangServices.IYuYangService)(this)).ContentCate_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.ContentCate_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageResponse> ContentCate_SelectPageAsync(Site.Service.YuYangService.YuYangServices.ContentCate_SelectPageRequest request) {
            return base.Channel.ContentCate_SelectPageAsync(request);
        }
        
        public int ChapterVisits_Insert(Site.Service.YuYangService.YuYangServices.ChapterVisits obj) {
            return base.Channel.ChapterVisits_Insert(obj);
        }
        
        public System.Threading.Tasks.Task<int> ChapterVisits_InsertAsync(Site.Service.YuYangService.YuYangServices.ChapterVisits obj) {
            return base.Channel.ChapterVisits_InsertAsync(obj);
        }
        
        public int ChapterVisits_DeleteById(int Id) {
            return base.Channel.ChapterVisits_DeleteById(Id);
        }
        
        public System.Threading.Tasks.Task<int> ChapterVisits_DeleteByIdAsync(int Id) {
            return base.Channel.ChapterVisits_DeleteByIdAsync(Id);
        }
        
        public int ChapterVisits_UpdateById(Site.Service.YuYangService.YuYangServices.ChapterVisits obj) {
            return base.Channel.ChapterVisits_UpdateById(obj);
        }
        
        public System.Threading.Tasks.Task<int> ChapterVisits_UpdateByIdAsync(Site.Service.YuYangService.YuYangServices.ChapterVisits obj) {
            return base.Channel.ChapterVisits_UpdateByIdAsync(obj);
        }
        
        public Site.Service.YuYangService.YuYangServices.ChapterVisits ChapterVisits_SelectById(int Id) {
            return base.Channel.ChapterVisits_SelectById(Id);
        }
        
        public System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.ChapterVisits> ChapterVisits_SelectByIdAsync(int Id) {
            return base.Channel.ChapterVisits_SelectByIdAsync(Id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageResponse Site.Service.YuYangService.YuYangServices.IYuYangService.ChapterVisits_SelectPage(Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageRequest request) {
            return base.Channel.ChapterVisits_SelectPage(request);
        }
        
        public System.Collections.Generic.List<Site.Service.YuYangService.YuYangServices.ChapterVisits> ChapterVisits_SelectPage(string cloumns, int pageIndex, int pageSize, string orderBy, string where, out int rowCount) {
            Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageRequest inValue = new Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageRequest();
            inValue.cloumns = cloumns;
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderBy = orderBy;
            inValue.where = where;
            Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageResponse retVal = ((Site.Service.YuYangService.YuYangServices.IYuYangService)(this)).ChapterVisits_SelectPage(inValue);
            rowCount = retVal.rowCount;
            return retVal.ChapterVisits_SelectPageResult;
        }
        
        public System.Threading.Tasks.Task<Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageResponse> ChapterVisits_SelectPageAsync(Site.Service.YuYangService.YuYangServices.ChapterVisits_SelectPageRequest request) {
            return base.Channel.ChapterVisits_SelectPageAsync(request);
        }
    }
}
